### ISSUE TITLE
Reference version number not set properly

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#170]
Under site-packages I deleted the entire RobotFramework_TestsuitesManagement folder.

Within the cloned GitHub repository sources of the RobotFramework_TestsuitesManagement I increased the package version from von **0.6.1** to **2.0.0**.

With setup.py I installed this version.

Because the GitHub is stand-alone (= outside the context of RobotFramework AIO) I expect now to have a stand-alone installation of the RobotFramework_TestsuitesManagement.

I wonder to find also in this installation a file CConfig.py with following entries:

```
AIO_BUNDLE_NAME = "RobotFramework AIO"
VERSION         = "0.7.0"
VERSION_DATE    = "03.2023"
```

These entries I would not expect in a stand-alone installation.

I execute a robot test with following requirement:

`"Maximum_version" : "1.0.0"`

The test is executed with result PASSED. That's wrong, because the reference version should be the version of the package, and this version is with 2.0.0 higher than allowed.

I decrease the requirement to

`"Maximum_version" : "0.6.0"`

and repeat the test. Outcome:

```
The test execution requires maximum RobotFramework AIO version '0.6.0'
but the installed RobotFramework AIO version is younger       '0.7.0'
```

That's also wrong, because I have no RobotFramework AIO installed on my computer.

I would expect something like:

```
The test execution requires maximum RobotFramework_TestsuitesManagement version '0.6.0'
but the installed RobotFramework_TestsuitesManagement version is younger       '0.7.0'
```

The handling of the two different version numbers used as reference for the version check, must be improved.

And also:

The log file contains following line:

`Set suite metadata 'version' to value '0.7.0'`

Because of two different version numbers are involved in the version check please add an information about the meaning of this 'version'.

Something like:

`Set suite metadata 'version' of RobotFramework AIO to value ...`
or
`Set suite metadata 'version' of RobotFramework_TestsuitesManagement to value ...`

Only calling it `'version'` is not helpful, because no one will know: Which version?

**Comment by ngoan1608** [comment]
Hi @test-fullautomation ,
Hi @HolQue ,

I have confused about versions usage now and need your confirmation to not make the wrong implementation.

We have implemented to used AIO version (bundle version) for:
1. Version check which is defined (min, max) in configuration `*.json` file
2. Robot metadata setting `version` (as Holger' observation)
3. Getting AIO version with command line:
    + `$RobotPythonPath/python -m RobotFramework_TestsuitesManagement.version` 
    + `$RobotScriptPath/robfwaio_version` 
    + `robot -aio` (only Linux)

And now the implementation is changed:
- **RobotFramework_TestsuitesManagement**'s version will be used for **1** and **2** 
- **RobotFramework_TestsuitesManagement** info is used instead of **RobotFramework AIO** for logging messages (version check and metadata setting).
- The AIO version (bundle version) will be only used for **3**.

Please give your idea about this point. Then I can update accordingly.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi @ngoan1608,

please contact @HolQue , he as an agreed proposal which solves the problem partly.

Thank you,
 Thomas

**Comment by HolQue** [comment]
Solved with https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/183
