### ISSUE TITLE
Failed self test of TestsuitesManagement

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#212]
Especially:

- TSM_0064-(VARIANT_HANDLING)-[BADCASE]
- TSM_0252-(NESTED_CONFIG)-[BADCASE]

Reason:

Reduced error messages. Therefore the log file comparison fails.

- TSM_0064-(VARIANT_HANDLING)-[BADCASE]

**Previously:** `UNKNOWN - Could not set variable 'params['global']['teststring_bench']' with value 'I am the 'bench1' configuration of tsm-test'! Reason: name 'params' is not defined`
**Now:** `UNKNOWN - name 'params' is not defined`

This looks like the reason itself is still available, but not the error message itself.

- TSM_0252-(NESTED_CONFIG)-[BADCASE]

**Previously:** `Could not set variable 'params['global']['dTestDict']['I-am-not-existing']['I-am-not-existing']' with value 'Val_1'! Reason`
**Now**: _This error message is missing completely now_

Another unwanted side effect: The robot test is executed.

Seems that the synchronization between the JsonPreprocessor and the TestsuitesManagement is improper.

In case of errors in JSON files, the JsonPreprocessor throws an exception. I would expect, that the exception is catched by the TestsuitesManagement and I would expect, that the TestsuitesManagement writes the reason for the exception to the log files.

It has to be investigated why this does not happen any more for TSM_0064 and TSM_0252.

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your finding!
When implemented enhancement [#74 “implicite creation of data structures”](https://github.com/test-fullautomation/python-jsonpreprocessor/issues/74) of JsonPreprocessor package, I forgot handling an error in case a highest element of Json object is not exist. That the reason you observed the error message is missing in Testsuitemanagement caused the exception in JsonPreprocessor was not catched.  

Due to the enhancement #74, we have to revise the test case ID TSM_0252, because with enhancement #74 if we define “params['global']['dTestDict']['I-am-not-existing']['I-am-not-existing']”, the JsonPreprocessor will create new element 'I-am-not-existing'.

I pushed [the change](https://github.com/test-fullautomation/python-jsonpreprocessor/commit/05227b28eaea9fe5f4bbb6c9e1f264b94d29e9b2) to JsonPreprocessor to fix this issue.

Thank you,
Son

**Comment by HolQue** [comment]
Status update:

* Issue with TSM_0064 is fixed in latest JsonPreprocessor code
* TSM_0252 has been removed from self test (because is invalid with introduction of implicit creation of data structures)
* Successor of TSM_0252 is TSM_1100 (implicit creation of data structures), but TSM_1100 fails.

Pull request and issue will follow.

**Comment by HolQue** [comment]
https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/214

**Comment by test-fullautomation** [comment]
Hi @namsonx ,
what is the status of this ticket?
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Son waits for retest from Holger.

**Comment by HolQue** [comment]
Accordingly to

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/212#issuecomment-1715718368

some aspects of this issue are solved, and what is still open (TSM_1100) is handled in successor:

https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/214
(https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/212#issuecomment-1715817346)

This issue can be solved.

**Comment by test-fullautomation** [comment]
solved with version 0.10.0
