### ISSUE TITLE
Robot testcase "Check maximum version" failed due to hardcoded max version "0.5.2"

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/robotframework-testsuitesmanagement#88]
Hi,

The Robot testcase "Testsuites_Management_Test_02"  under **test** folder which verifying the max version in configuration failed when executing **aio-test-trigger** due to max version check.

Root cause: the hardcoded value "0.5.2" is used in config file and Robot test for comparison.

Thank you,
Ngoan

**Comment by HolQue** [comment]
Solved by https://github.com/test-fullautomation/robotframework-testsuitesmanagement/pull/89

**Comment by HolQue** [comment]
Some additional hints: The `test` folder is an example only. I introduced this folder while implementing the test trigger. There is also an `atest` folder existing. Because I was not familiar with the content and also did not know about the status, I decided to make the `test` folder my own playground to check, if the test trigger works also for the test suites management.

But this parallel existence of two different test folders cannot not be the final solution.

I urgently suggest to merge the content into one final test folder. But this has to be done by the one who is responsible for the tests.

**Comment by ngoan1608** [comment]
> Some additional hints: The `test` folder is an example only. I introduced this folder while implementing the test trigger. There is also an `atest` folder existing. Because I was not familiar with the content and also did not know about the status, I decided to make the `test` folder my own playground to check, if the test trigger works also for the test suites management.
> 
> But this parallel existence of two different test folders cannot not be the final solution.
> 
> I urgently suggest to merge the content into one final test folder. But this has to be done by the one who is responsible for the tests.

Hi Holger,

Thank you for your hints!
I am just getting familiar with **aio-test-trigger** to prepare for CT workflow by executing the default _testtrigger_config.json_ (which point to this **test** folder).
I agree that the content should be merge for this repo.
I am creating the separated issue for that request.

Thank you,
Ngoan

**Comment by ngoan1608** [comment]
#90 has been created for merging test folders.

**Comment by HolQue** [comment]
maximum version is adapted; ticket can be closed

**Comment by test-fullautomation** [comment]
solved and already merged with #89
