### ISSUE TITLE
Side effects of improper command lines

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#94]
By mistake I used `local_config` instead of `config_file` to select a variant specific parameter configuration file in command line:

`--variable local_config:"../config/exercise-08_config_variant1.json"`

This has some interesting side effects.

At first: This is accepted. Does not cause any syntax issues.

Probably because `config_file` is not used (and also not `variant`) the default variant configuration is loaded - and overwritten by the (local) variant1 configuration. The variant specific parameter has variant1 values. OK so far.

But in log file this is labelled with 'level 2'. That's wrong.

```
Running with configuration level 2
Parameters loaded from 'C:\RobotTest\projects\ROBFW_AIO\robotframework-tutorial\900_building_testsuites\exercise-08\config\exercise-08_config_default.json'
Suite Path: C:\RobotTest\projects\ROBFW_AIO\robotframework-tutorial\900_building_testsuites\exercise-08\testsuites
CfgFile Path: C:\RobotTest\projects\ROBFW_AIO\robotframework-tutorial\900_building_testsuites\exercise-08\config\exercise-08_config_default.json
Local config file: C:\RobotTest\projects\ROBFW_AIO\robotframework-tutorial\900_building_testsuites\exercise-08\config\exercise-08_config_variant1.json
```

**Comment by namsonx** [comment]
Hello Holger,

Thank you for your mistake :) 
I will improve it

Thank you,
Son

**Comment by namsonx** [comment]
Hello @HolQue ,

Can you please also share the testsuite you were using in this case?

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

I used the tutorial files:

https://github.com/test-fullautomation/robotframework-tutorial/tree/develop/900_building_testsuites/exercise-08

**Comment by namsonx** [comment]
Hello Holger,

I saw you put ../config/exercise-08_variants.json as the input parameter of testsuite_setup, it means that the configuration level 2 is enable.
By your mistake, you used 'local_config' instead of 'config_file' to select a variant specific parameter, so our testsuitesmanagement understands user execute robot test with configuration level 2 and local_config also is set.
For that the log show "Running with configuration level 2" is correct in this case.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

you are right! I was confused about my own use case ;-)
