### ISSUE TITLE
Unfavorable error message in case of improper command line

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-testsuitesmanagement#95]
By mistake I used `config_file` instead of `local_config` to select a local configuration file in command line:

`--variable config_file:"../localconfig/exercise-08_localconfig_bench1.json"`

This causes the following error message in console:

`Unknown exception occurs. Details: Could not set variable 'params['global']['teststring_bench']' with value 'I am the 'bench1' configuration of exercise 08'!`

That's not wrong - but also not really helpful in this context. Because this error message does not point to the root cause of the problem.

But what is the root cause? The local config file is a fragment only and does not contain mandatory parameters like the welcome string and the project. Therefore the file is not loaded. Additionally we loose the initial definition of the global parameter `teststring_bench`. Most probably the complete `global/params` dictionary does not exist. Therefore the local configuration cannot refer to this.

But I do not understand why a local configuration is involved here? In my opinion at first it should be checked if all required parameters are present. If this is not the case, then the configuration file is invalid. The computation can be stopped now. No need to continue with taking a look at further sources of configuration parameters.

The error message should tell the user that because of missing mandatory parameters the selected configuration file is invalid and cannot be used.

Outcome: Test execution stops with test result UNKNOWN.

That a parameter cannot be set is a follow up error only - and irrelevant in this error scenario.

Unfortunately also the log file does not help:

```
UNKNOWN - Unknown exception occurs. Details: Could not set variable 'params['global']['teststring_bench']' with value 'I am the 'bench1' configuration of exercise 08'!
DEBUG - Traceback (most recent call last):
  File "D:\RobotFramework\python39\lib\site-packages\RobotFramework_TestsuitesManagement\__init__.py", line 67, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "D:\RobotFramework\python39\lib\site-packages\robotlibcore.py", line 105, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
  File "D:\RobotFramework\python39\lib\site-packages\RobotFramework_TestsuitesManagement\Keywords\CSetup.py", line 70, in testsuite_setup
    BuiltIn().unknown(CConfig.sLoadedCfgError)
  File "D:\RobotFramework\python39\lib\site-packages\robotframework-4.1.3-py3.9.egg\robot\libraries\BuiltIn.py", line 562, in unknown
    raise UnknownAssertionError(msg) if msg else UnknownAssertionError()

```

**Comment by test-fullautomation** [comment]
We should think about if it is possible to recognize the type of file to give immediately a proper message.

Maybe it helps if we do an additional node:
```
{ 'localconfig' : {
                    }
}
```

The availability can be an indicator which type of file it is.
Maybe you have a better proposal.

**Comment by HolQue** [comment]
```
{
   "configtype" : "local_config"
}
```

Available config types: variant_config, parameter_config, local_config

**Comment by test-fullautomation** [comment]
Hm...
for me there is only a local_config.
Let us discuss this, before we do any change.

**Comment by HolQue** [comment]
Or maybe in this way:

Configuration files that are either accessed by `config_file` or by a variant configuration file or by a `config` folder must at top level contain mandatory keys like `WelcomeString`, `Project` and `TargetName`. Additionally they are allowed to contain optional keys like `Maximum_version`, `Minimum_version` and `params`.

Configuration files that are either imported or accessed by `local_config` or by `ROBOT_LOCAL_CONFIG` must not contain these keys (`WelcomeString`, `Project`, `TargetName`, `Maximum_version`, `Minimum_version `and `params`).

Variant configuration files passed to the suite setup, must also not contain these keys (`WelcomeString`, `Project`, `TargetName`, `Maximum_version`, `Minimum_version `and `params`), but have to contain at least a default variant (key `default` with subkeys `name` and `path`).

Any violations of these rules should cause an "invalid configuration file error".

Variant names in command line (`variant`) should be checked against characters that are not allowed inside names (like path separators). This rule would detect errors like
`--variable variant:"D:/path/to/configfile.json"`
where accidently a path to a config file is provided instead of a variant name.

**Comment by namsonx** [comment]
Hello Holger,

Now we changed "additionalProperties" from true to false, so the scenario you described above the schema check will fail.
Could you please check this scenario with branch "namsonx/enhancement/80/JSON_schema_validation_update"?

Thank you,
Son

**Comment by HolQue** [comment]
Hello Son,

have you tested this? On my computer the error still occur. Why shall this issue be solved with additionalProperties set to false? The problem is not, that additional properties are defined - but not allowed. The problem is other way round: Required parameters are missing - because the local configuration, handed over by mistake, does not contain them.

Seems that
`"required": ["Project", "WelcomeString", "TargetName"],`
does not work in this use case.

**Comment by test-fullautomation** [comment]
Hi Son,

in general you should verify as early as possible the validity of all input files which you allow with your testsuites-management implementation.
This applies for all input sources (part of robot source, command line, ...)
Proposal:
* if you expect a config file, then do immediately first a schema check and stop immediately execution with a speaking error message in case of violation.
* In order to avoid that somebody accidentally provides to --localconfig a (full) config file you can do a schema check against our schema. If this passes successfully, then we know that the provided file was definitely a (full) config file and we can raise a nice error message. (expect localconfig, but got config file instead...)
* The same applies for imported files. They musn't fit to the schema, too.

Please implement accordingly.
Please ask in case of concerns.

Thank you,
 Thomas

**Comment by namsonx** [comment]
> Hello Son,
> 
> have you tested this? On my computer the error still occur. Why shall this issue be solved with additionalProperties set to false? The problem is not, that additional properties are defined - but not allowed. The problem is other way round: Required parameters are missing - because the local configuration, handed over by mistake, does not contain them.
> 
> Seems that `"required": ["Project", "WelcomeString", "TargetName"],` does not work in this use case.

Hello Holger,

It seems that I commented in wrong issue, this comment I was going to add to #80 :)
Sorry for my mistake, I will implement the change for this issue soon.

Thank you,
Son

**Comment by namsonx** [comment]
Hello Holger and Thomas,

"By mistake I used config_file instead of local_config to select a local configuration file in command line:

--variable config_file:"../localconfig/exercise-08_localconfig_bench1.json"

This causes the following error message in console:

Unknown exception occurs. Details: Could not set variable 'params['global']['teststring_bench']' with value 'I am the 'bench1' configuration of exercise 08'!

That's not wrong - but also not really helpful in this context. Because this error message does not point to the root cause of the problem."

For this case, the error message show "Could not set variable 'params['global']['teststring_bench']'" instead of check JSON schema first because:
* By mistake user set local config file to "config_file" variable, so testsuitesmanagement will handle local config file as configuration file. This local config file first is handled by jsonpreprocessor package, and during handling by jsonpreprocessor, the jsonpreprocessor recognizes that  the variable 'params['global']' was not exist.
* It means this error message are raise during loading Json configuration file which is handled by the jsonpreprocessor.

To use JSON schema validator, firstly we have to parse the Json object from Json file, and in this case we're using Jsonpreprocessor. So that the reason Json schema check does not yet active in this case.

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

then you have to make it active

When you get a file with `--variable config_file`, then you make a schema check with this file.

What is the problem?

**Comment by namsonx** [comment]
> 

Hello Holger,

The problem is we offer user some advance features in JSON configuration file such as import other JSON files, adding the comments in JSON file, overwriting the value of existing elements of JSON configuration file,... which are handled by JsonPreprocessor package. So, before doing schema check, JSON configuration file has to be handled by JsonPreprocessor. And during handle by JsonPreprocessor, it recognizes that a nested parameter is not defined before (not available).

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Son,

you are right. I overlooked that preprocessing is not possible due to the fact that a file is possibly only a fragment of a config file which can contain in this case JSON syntax violations.

Proposal instead:

Provide a function e.g. `isConfigFile` which reads a config file and makes a string search for our mandatory keys (e.g.Project). If there is a hit, then return True.

* if you expect a config file, then do immediately first `isConfigFile` and stop immediately execution with a speaking error message in case of violation.
* In order to avoid that somebody accidentally provides to --localconfig a (full) config file you can do `isConfigFile`. If this passes successfully, then we know that the provided file was definitely a (full) config file and we can raise a nice error message. (expect localconfig, but got config file instead...)
* The same applies for imported files. They musn't fit to the schema, too.

This is just a precheck to create nice, helpingerror messages.
Therefore code which uses `isConfigFile` need to be in a try/except block. If it crashes due to whatever reason, then just `pass` without any message.  Doesn't matter when the check didn't work.

Thank you,
 Thomas

**Comment by HolQue** [comment]
OK: No traceback any more
NOT OK: Still unfavorable error message

**Comment by test-fullautomation** [comment]
Hi Son,
what is the status of this issue?
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Thomas,

'''
By mistake I used config_file instead of local_config to select a local configuration file in command line:

--variable config_file:"../localconfig/exercise-08_localconfig_bench1.json"
'''
If we provide a function e.g. isConfigFile which reads a config file and makes a string search for our mandatory keys (e.g.Project). 
    - This solution will not work if mandatory fields are located in imported file because imported files are also handled in JsonPreprocessor package :(

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son,

very good finding! Seems that the problem is much more difficult than expected.

Let me share some thoughts. I see two possibilities.

**First one:**

It is not allowed any more to get mandatory keys by imported files. Every parameter configuration file needs to have the mandatory keys inside immediately. But it's obvious: This is a very unfavorable limitation and therefore not acceptable.

**Second one:**

`config_file` and `local_config` are command line parameters of the testsuites management. Behind both parameters there is a certain expectation:

* `config_file` = _mandatory parameters expected_
* `local_config` = _mandatory parameters not expected_

The testsuites management knows about this expectation. And now the testsuites management calls the JsonPreprocessor with an additional input parameter that defines the expectation. To support this, the implementation of the JsonPreprocessor needs to be adapted.

The JsonPreprocessor has to support something that we may call "pre check". When then the testsuites management calls the JsonPreprocessor with a certain configuration file to parse and now additionally with the hint, that a `config_file` is expected (and not a `local_config`) and therefore mandatory parameters are expected to be defined inside, then the JsonPreprocessor should at first resolve all imports and check if these  parameters are available - I mean: the corresponding keys like `"WelcomeString"`, `"Maximum_version"` and so on (= pre check).

**And the JsonPreprocessor has to do this BEFORE he tries to resolve any parameters (${...}) to get the concrete value.**

This also means: The discussed function `isConfigFile` has to be moved from the testsuites management to the JsonPreprocessor.

What do you think? Might this be a solution?

**Comment by HolQue** [comment]
Something additional came into my mind:

Also all users of the stand-alone JsonPreprocessor might have the same problems - and therefore the need to get a pre check of the JSON file. We should make it an official feature for the JsonPreprocessor.

The interface of the JsonPreprocessor should be extended by two further (optional) input parameters:

* list of keys expected
* list of keys not expected (and not allowed)

And to point it out again: This is related to the existence of keys only ("pre check" character), and has at this early stage nothing to do with the possibility to resolve all parameters (this will still be the already implemented second step). This pre check should be text based (static code analysis) and should be done before any further JSON based parsing and before any schema validation.

**Comment by namsonx** [comment]
Hello Holger,

Thank you very much for your valuable suggestion, I would go with your second suggestion.
I will implement and create a pull-request for this ticket.

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi @namsonx, @HolQue,

please don't change anything. Let us discuss before. 

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
@namsonx   : What is the status of this issue?
@HolQue

**Comment by namsonx** [comment]
Hello Thomas,

This improvement was implemented in the commit [3a2fcd8f6](https://github.com/test-fullautomation/robotframework-testsuitesmanagement/commit/3a2fcd8f6f437b7446b89dadcddac52f136a22e4)

Thank you,
Son

**Comment by HolQue** [comment]
Hi Son, Hi Thomas,

I am confused now :-(

There is a problem, I made a proposal, you asked to discuss before further implementation, nothing happened - and suddenly the issue shall be solved?

No! The issue is not solved. The error message is mostly the same like before and still does not give useful information about what is the concrete problem behind the technical details in the error message.

**Comment by test-fullautomation** [comment]
Hi Holger,
thank you for the status :-)
I shift this to 0.10.0. This is not critical for 0.9.0
Thank you,
 Thomas

**Comment by namsonx** [comment]
Hello Holger,

It was the long discussion on this ticket which mentions about the case ```By mistake I used config_file instead of local_config to select a local configuration file in command line```

Current behavior in this case is:

1. In case the variable ```variant``` is set with configuration level 2, the error message is:
```
20240715 15:17:31.243 - ERROR - Redundant settings detected in command line: Parameter 'variant' is used together with parameter 'config_file'.
20240715 15:17:31.244 - ERROR - ---> It is not possible to use both together, because they belong to the same feature (the variant selection).
20240715 15:17:31.245 - ERROR - ---> Please remove one of them.
20240715 15:17:31.247 - UNKNOWN - Unable to load the test configuration. The test execution will be aborted!
```

2. For other cases, the error message is:
```
20240715 15:20:16.868 - ERROR - Required parameter 'Project' is missing in file 'C:\Users\mas2hc\Desktop\data_storage\workspace\ROBFWAIO-OSS\robotframework-testsuitesmanagement\atest\atest_component\builtin_variable\testsuites\config\local_config.json'.
20240715 15:20:16.870 - ERROR - JSON schema validation failed!
20240715 15:20:16.872 - UNKNOWN - Unable to load the test configuration. The test execution will be aborted!
```

Could you please help me verify this ticket again?

Thank you!,
Son

**Comment by namsonx** [comment]
Ready for **sprint 0.13.0 [09.08.24](jsonpreprocessor / tsm)**
